### ISSUE TITLE
Relaxing the 'Missing space after 'function' issue

### ISSUE THREAD

**Issue by tciuro** [desandro/jshint.tmbundle#1]
Hi David,

Your fork works great. Thanks so much. I have a question though: TextMate formats the code so that there is no space after function. As a result, I see lots of:

```
Missing space after 'function'.
exports.doSomething = function(req, res) {
```

Do you know what I should change in my .jshintrc file to silence this warning? Or perhaps change the formatter to add this space? I have tried to Google for this, but I'm struggling to find a valid suggestion.

It's quite annoying because every time I format the code, this issue shows up :-/

Thanks!

**Comment by desandro** [comment]
I think whitespace is the flag you want to disable. `"whitespace": false`
